# Generated by Django 6.0.3 on 2026-06-10 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TableCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_collaborators', to='ledger.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('table', 'user')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_tables', through='ledger.TableCollaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
