# Generated by Django 6.0.3 on 2026-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_ledgeruser_user_table_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
