# Generated by Django 6.0.3 on 2026-07-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_ledgeruser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_player', models.CharField(max_length=100)),
                ('to_player', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ledger.table')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
